### ISSUE TITLE
Compaction modelling using a probabilistic compaction model

### ISSUE THREAD

**Issue by PatrickMakuluni** [inlab-geo/cofi-gallery#1]
Hi team, I'd like my CoFI example to be added to the CoFI gallery. Here's the information about my example:
- Title: Compaction modelling using a probabilistic compaction model
- Link to my example: <https://github.com/PatrickMakuluni/CoFI-Example-Compaction-Model>
- Link to a thumbnail image: <https://github.com/PatrickMakuluni/CoFI-Example-Compaction-Model/blob/main/Final%20Model.png>

## Checklist
- [x] I have included the title of my example above
- [x] The example uses CoFI to work on an inference problem
- [x] I have included a link to either a notebook or a script above
- [x] I have included a link to a thumbnail image above
- [x] The thumbnail image is in PNG format

**Comment by jwhhh** [comment]
Updated to page: https://cofi.readthedocs.io/en/latest/gallery/generated/index.html
